solargraph:
  extends:
    file: docker-compose.yml
    service: app
  command: solargraph socket --host=0.0.0.0 --port=7658
  working_dir: $PWD
  environment:
    GEM_HOME: "$PWD/vendor/bundle"
  volumes:
    - .:$PWD:cached,rw
  ports:
   - 7658:7658